id = "pascal"
name = "Pascal"
version = "0.1.1-oisanjaya"
schema_version = 1
authors = ["Guilherme Caldas <gcaldas@chemis.tech>, Rio Sanjaya <oisanjaya@gmail.com>"]
description = "Pascal language support."
repository = "https://github.com/oisanjaya/zed-pascal/tree/feature"

[grammars.pascal]
repository = "https://github.com/oisanjaya/tree-sitter-pascal"
rev = "90877056cab8a9934b6e8d1564fc52f79f9f0d5b"

[language_servers.pascal]
name = "pascal-language-server"
languages = ["Pascal"]
